### ISSUE TITLE
funy bug

### ISSUE THREAD

**Issue by Nameless9000** [MattLawz/coinworks#91]
lol

[example of this issue](https://coinworks.club/doge/0x692077696c6c206b696c6c20796f75722066616d%26%2F..%2F..%2Fhowdoisuckoffadolfhitler%2F..%2Fmoneypls%2F..%2F3dloliporn%2F..%2Fblock%2F42069%3Fsize%3D69696969x69696969%26data%3Dhttps%253A%252F%252Fwww.youtube.com%252Fwatch%253Fv%253DbfBu2rV-aYs%26format%3Dsvg%26ecc%3DH%26color%3D26-32-44%26bgcolor%3Dffffff%26qzone%3D100%26margin%3D69%26sieghail%3Dlolsecure%26canburn%3Dchurches)

**Comment by MattLawz** [comment]
Obviously, you are not meant to use it for that purpose.

**Comment by Nameless9000** [comment]
> Obviously, you are not meant to use it for that purpose.

this can turn into a security issue if there is an open redirect on the qr code website or the blockchain website

**Comment by MattLawz** [comment]
> > Obviously, you are not meant to use it for that purpose.
> 
> this can turn into a security issue if there is an open redirect on the qr code website or the blockchain website

You literally cannot redirect anyone into a different site because there are no third-party untrusted sites that are being off-linked. The blockchain explorers won't display a random link as a valid address. In terms of the QR-Code, I have it set up to strictly the cryptocurrency type generation. So even if a malicious link was generated, it would not go anywhere if someone scanned it as it is using the crypto format: `crypto:address`, try scanning to my site with the BTC tag and tell me if it loads: 

https://coinworks.club/btc/mattlawz.dev

(It will automatically open your cryptocurrency wallet...)

**Comment by MattLawz** [comment]
Also diving deeper into the QR-Code address generator, you can see on my generation link how I am exactly calling the pacific cryptocurrency: `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=litecoin:`

**Comment by MattLawz** [comment]
Adding onto the above: 

https://github.com/MattLawz/coinworks/blob/b2426a53d7da1592857c30e164df414be8a16784/pages/ltc/%5Bpid%5D.tsx#L78

**Comment by MattLawz** [comment]
Hope you understand the concept
